version: "3"
services:
  notebook:
    image: giza-cli:latest
    container_name: giza-cli
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8888:8888
    command: bash
    tty: true 
    stdin_open: true
    volumes:
      - .:/home